//import { googleAI } from "../config/googleAi.js";
import imageKit from "../config/imageKit.js";
import Chat from "../models/chat.js";
import User from "../models/user.js";
import axios from 'axios'

// Text-based Ai chat message contriller
export const textMessageController = async(req, res) => {
    try {
        const userId = req.user._id;  // get user id from middleware
        const {chatId, prompt} = req.body;
        // check credits, as for text generation we deduct 1 credits
        if(req.user.credits < 1){
            return res.json({success:false, message: "You dont't have enough credits to use this feature"});
        }
        const chat = await Chat.findOne({userId, _id: chatId});
        if (!chat) return res.json({ success: false, message: "Chat not found" });
        // save user message
        chat.messages.push({
            role:'user', 
            content: prompt, 
            timestamp: Date.now(), 
            isImage: false
        });

        const {choices} = await openai.chat.completions.create({
            model: "gemini-3-flash-preview",
            messages: [
                {
                    role: "user",
                    content: prompt,
                },
            ],
        });

        const reply = {...choices[0].message, timestamp: Date.now(), isImage: false };
        res.json({success: true, reply});
        /*
            choices[0]
            AI may return multiple possible replies
            You take the first (best) one
        */

        chat.messages.push(reply);
        await chat.save();
        
        // for text we deduct one credit
        await User.updateOne({_id: userId} , {$inc: {credits: -1}});

    } catch (error) {
        res.json({success:false, message: error.message});
    }
}

// image generation message controller
export const imageMessageController = async(req, res) => {
    try {
        const userId = req.user._id; 
        // check credits, as for image generation we deduct 2 credits
        if(req.user.credits < 2){
            return res.json({success:false, message: "You dont't have enough credits to use this feature"});
        }
        const {prompt, chatId, isPublished} = req.body;
        // Find Chat
        const chat = await Chat.findOne({userId, _id: chatId});
        // push user message
        chat.messages.push({
            role: "user",
            content: prompt,
            timestamp: Date.now(),
            isImage: false,
        });

        // Encode the prompt
        const encodedPrompt =  encodeURIComponent(prompt);
        // construct imageKit Ai generation url
        const generateImageUrl = `${process.env.IMAGEKIT_URL_ENDPOINT}/ik-genimg-prompt-${encodedPrompt}/Chat-ai-app/${Date.now()}.png?tr=w-800,h-800` /* ImageKit transform parameter, resize transform (800x800) */
        // generated by fetching imageKit
        const aiImageResponse = await axios.get(generateImageUrl, {responseType:"arraybuffer"})

        // convert to Base64
        const base64Image = `data:image/png;base64,${Buffer.from(aiImageResponse.data,"binary").toString('base64')}`;
        // upload to ImageKit media library
        const uploadResponse = await imageKit.upload({
            file: base64Image,
            fileName: `${Date.now()}.png`,
            folder: 'Chat-ai-app'
        });

        const reply = {
            role: 'assistant',
            content: uploadResponse.url,
            timestamp: Date.now(),
            isImage: true,
            isPublished
        }

        res.json({success: true, reply});
        
        chat.messages.push(reply);
        await chat.save();

        // for image generation deduct 2 credit
        await User.updateOne({_id: userId} , {$inc: {credits: -2}});

    } catch (error) {
        res.json({success: false, message: error.message});
    }
}
